import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/lastmile-ai-api-v-2",
    },
    {
      type: "category",
      label: "Dataset",
      items: [
        {
          type: "doc",
          id: "api/create-dataset",
          label: "Create Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-dataset-file",
          label: "Upload Dataset File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/finalize-single-dataset-file-upload",
          label: "Finalize Single Dataset File Upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset",
          label: "Get Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset-download-url",
          label: "Get Dataset Download URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset-view",
          label: "Get Dataset View",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-datasets",
          label: "List Datasets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/clone-dataset",
          label: "Clone Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/archive-dataset",
          label: "Archive Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-dataset-row",
          label: "Update Dataset Row",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-dataset-metadata",
          label: "Update Dataset Metadata",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluation",
      items: [
        {
          type: "doc",
          id: "api/evaluate",
          label: "Evaluate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/evaluate-dataset",
          label: "Evaluate Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/evaluate-run",
          label: "Evaluate Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-evaluation-run",
          label: "Get Evaluation Run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-evaluation-runs",
          label: "List Evaluation Runs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-metrics",
          label: "List Metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-metric",
          label: "Get Metric",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Experiment",
      items: [
        {
          type: "doc",
          id: "api/create-experiment",
          label: "Create Experiment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-experiment",
          label: "Get Experiment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-experiments",
          label: "List Experiments",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Fine Tune Job",
      items: [
        {
          type: "doc",
          id: "api/create-fine-tune-job",
          label: "Create Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-fine-tune-job",
          label: "Submit Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-fine-tune-job",
          label: "Get Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-fine-tune-job-status",
          label: "Get Fine Tune Job Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-fine-tune-jobs",
          label: "List Fine Tune Jobs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-base-models",
          label: "List Base Models",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Resource Permission",
      items: [
        {
          type: "doc",
          id: "api/can-viewer-do",
          label: "Can Viewer Do",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-role",
          label: "Get Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-applicable-permissions",
          label: "List Applicable Permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-assignable-roles",
          label: "List Assignable Roles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-resource-role-permissions",
          label: "List Resource Role Permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/add-resource-role-permission",
          label: "Add Resource Role Permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/change-resource-role-permission",
          label: "Change Resource Role Permission",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-resource-role-permission",
          label: "Remove Resource Role Permission",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Project",
      items: [
        {
          type: "doc",
          id: "api/create-project",
          label: "Create Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-project",
          label: "Get Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-project-summary",
          label: "Get Project Summary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-default-project",
          label: "Get Default Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-projects",
          label: "List Projects",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/update-project-metadata",
          label: "Update Project Metadata",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/add-project-members",
          label: "Add Project Members",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-project-members",
          label: "Remove Project Members",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/change-project-member-role",
          label: "Change Project Member Role",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-assignable-project-member-roles",
          label: "List Assignable Project Member Roles",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-project-members",
          label: "List Project Members",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Pseudo Label Job",
      items: [
        {
          type: "doc",
          id: "api/create-pseudo-label-job",
          label: "Create Pseudo Label Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-pseudo-label-job",
          label: "Submit Pseudo Label Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-pseudo-label-job-status",
          label: "Get Pseudo Label Job Status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/createdatasetrequest",
          label: "CreateDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createdatasetresponse",
          label: "CreateDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dataset",
          label: "Dataset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/timestamp",
          label: "Timestamp",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetcolumninfo",
          label: "DatasetColumnInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetlabelstate",
          label: "DatasetLabelState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploaddatasetfilerequest",
          label: "UploadDatasetFileRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploaddatasetfileresponse",
          label: "UploadDatasetFileResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/s-3-presignedpost",
          label: "S3PresignedPost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldsentry",
          label: "FieldsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finalizesingledatasetfileuploadrequest",
          label: "FinalizeSingleDatasetFileUploadRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finalizesingledatasetfileuploadresponse",
          label: "FinalizeSingleDatasetFileUploadResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetrequest",
          label: "GetDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetresponse",
          label: "GetDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetdownloadurlrequest",
          label: "GetDatasetDownloadURLRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetdownloadurlresponse",
          label: "GetDatasetDownloadURLResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetviewrequest",
          label: "GetDatasetViewRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetrowfilter",
          label: "DatasetRowFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/allof",
          label: "AllOf",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/anyof",
          label: "AnyOf",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetfieldvaluepredicate",
          label: "DatasetFieldValuePredicate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stringcriteria",
          label: "StringCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/numericcriteria",
          label: "NumericCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stringlistcriteria",
          label: "StringListCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetviewresponse",
          label: "GetDatasetViewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetview",
          label: "DatasetView",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datarow",
          label: "DataRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-value",
          label: "google.protobuf.Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/struct",
          label: "Struct",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldsentry",
          label: "FieldsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvalue",
          label: "ListValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsrequest",
          label: "ListDatasetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsrequestfilters",
          label: "ListDatasetsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsresponse",
          label: "ListDatasetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clonedatasetrequest",
          label: "CloneDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clonedatasetresponse",
          label: "CloneDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/archivedatasetrequest",
          label: "ArchiveDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/archivedatasetresponse",
          label: "ArchiveDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatedatasetrowrequest",
          label: "UpdateDatasetRowRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldupdatesentry",
          label: "FieldUpdatesEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatedatasetrowresponse",
          label: "UpdateDatasetRowResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatedatasetmetadatarequest",
          label: "UpdateDatasetMetadataRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updatedatasetmetadataresponse",
          label: "UpdateDatasetMetadataResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluaterequest",
          label: "EvaluateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metric",
          label: "Metric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluateresponse",
          label: "EvaluateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluatedatasetrequest",
          label: "EvaluateDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluatedatasetresponse",
          label: "EvaluateDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metricscores",
          label: "MetricScores",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluaterunrequest",
          label: "EvaluateRunRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluaterunresponse",
          label: "EvaluateRunResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getevaluationrunrequest",
          label: "GetEvaluationRunRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getevaluationrunresponse",
          label: "GetEvaluationRunResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluationrun",
          label: "EvaluationRun",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metricaggregate",
          label: "MetricAggregate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listevaluationrunsrequest",
          label: "ListEvaluationRunsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listevaluationrunsrequestfilters",
          label: "ListEvaluationRunsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listevaluationrunsresponse",
          label: "ListEvaluationRunsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmetricsrequest",
          label: "ListMetricsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmetricsresponse",
          label: "ListMetricsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmetricrequest",
          label: "GetMetricRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmetricresponse",
          label: "GetMetricResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createexperimentrequest",
          label: "CreateExperimentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createexperimentresponse",
          label: "CreateExperimentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/experiment",
          label: "Experiment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getexperimentrequest",
          label: "GetExperimentRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getexperimentresponse",
          label: "GetExperimentResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listexperimentsrequest",
          label: "ListExperimentsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listexperimentsrequestfilters",
          label: "ListExperimentsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listexperimentsresponse",
          label: "ListExperimentsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createfinetunejobrequest",
          label: "CreateFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejobconfig",
          label: "FineTuneJobConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createfinetunejobresponse",
          label: "CreateFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitfinetunejobrequest",
          label: "SubmitFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitfinetunejobresponse",
          label: "SubmitFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobrequest",
          label: "GetFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobresponse",
          label: "GetFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejob",
          label: "FineTuneJob",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejobresult",
          label: "FineTuneJobResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/trainingprogress",
          label: "TrainingProgress",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/modelfile",
          label: "ModelFile",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobstatusrequest",
          label: "GetFineTuneJobStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobstatusresponse",
          label: "GetFineTuneJobStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsrequest",
          label: "ListFineTuneJobsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsrequestfilters",
          label: "ListFineTuneJobsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsresponse",
          label: "ListFineTuneJobsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbasemodelsrequest",
          label: "ListBaseModelsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbasemodelsresponse",
          label: "ListBaseModelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/model",
          label: "Model",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metricbasemodel",
          label: "MetricBaseModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/modelcard",
          label: "ModelCard",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/valuesentry",
          label: "ValuesEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/canviewerdorequest",
          label: "CanViewerDoRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/canviewerdoresponse",
          label: "CanViewerDoResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/candoactioncheck",
          label: "CanDoActionCheck",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getrolerequest",
          label: "GetRoleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getroleresponse",
          label: "GetRoleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/role",
          label: "Role",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/roleuser",
          label: "RoleUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listapplicablepermissionsrequest",
          label: "ListApplicablePermissionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listapplicablepermissionsrequestfilters",
          label: "ListApplicablePermissionsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listapplicablepermissionsresponse",
          label: "ListApplicablePermissionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/permission",
          label: "Permission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignablerolesrequest",
          label: "ListAssignableRolesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignablerolesrequestfilters",
          label: "ListAssignableRolesRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignablerolesresponse",
          label: "ListAssignableRolesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listresourcerolepermissionsrequest",
          label: "ListResourceRolePermissionsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listresourcerolepermissionsresponse",
          label: "ListResourceRolePermissionsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rolepermission",
          label: "RolePermission",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addresourcerolepermissionrequest",
          label: "AddResourceRolePermissionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addresourcerolepermissionresponse",
          label: "AddResourceRolePermissionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeresourcerolepermissionrequest",
          label: "ChangeResourceRolePermissionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeresourcerolepermissionresponse",
          label: "ChangeResourceRolePermissionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/removeresourcerolepermissionrequest",
          label: "RemoveResourceRolePermissionRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/removeresourcerolepermissionresponse",
          label: "RemoveResourceRolePermissionResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createprojectrequest",
          label: "CreateProjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createprojectresponse",
          label: "CreateProjectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/project",
          label: "Project",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectrequest",
          label: "GetProjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectresponse",
          label: "GetProjectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectsummaryrequest",
          label: "GetProjectSummaryRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectsummaryresponse",
          label: "GetProjectSummaryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/projectsummary",
          label: "ProjectSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/projectevaluationrunmetricsummary",
          label: "ProjectEvaluationRunMetricSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/statisticalmetricsentry",
          label: "StatisticalMetricsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluationrunsmetricsummaryaggregate",
          label: "EvaluationRunsMetricSummaryAggregate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdefaultprojectrequest",
          label: "GetDefaultProjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdefaultprojectresponse",
          label: "GetDefaultProjectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsrequest",
          label: "ListProjectsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsrequestfilters",
          label: "ListProjectsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsresponse",
          label: "ListProjectsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateprojectmetadatarequest",
          label: "UpdateProjectMetadataRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/updateprojectmetadataresponse",
          label: "UpdateProjectMetadataResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addprojectmembersrequest",
          label: "AddProjectMembersRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/addprojectmembersresponse",
          label: "AddProjectMembersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/removeprojectmembersrequest",
          label: "RemoveProjectMembersRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/removeprojectmembersresponse",
          label: "RemoveProjectMembersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeprojectmemberrolerequest",
          label: "ChangeProjectMemberRoleRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/changeprojectmemberroleresponse",
          label: "ChangeProjectMemberRoleResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignableprojectmemberrolesrequest",
          label: "ListAssignableProjectMemberRolesRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignableprojectmemberrolesrequestfilters",
          label: "ListAssignableProjectMemberRolesRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listassignableprojectmemberrolesresponse",
          label: "ListAssignableProjectMemberRolesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectmembersrequest",
          label: "ListProjectMembersRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectmembersrequestfilters",
          label: "ListProjectMembersRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectmembersresponse",
          label: "ListProjectMembersResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/projectmember",
          label: "ProjectMember",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpseudolabeljobrequest",
          label: "CreatePseudoLabelJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pseudolabeljobconfig",
          label: "PseudoLabelJobConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/prompttemplate",
          label: "PromptTemplate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpseudolabeljobresponse",
          label: "CreatePseudoLabelJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitpseudolabeljobrequest",
          label: "SubmitPseudoLabelJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitpseudolabeljobresponse",
          label: "SubmitPseudoLabelJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getpseudolabeljobstatusrequest",
          label: "GetPseudoLabelJobStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getpseudolabeljobstatusresponse",
          label: "GetPseudoLabelJobStatusResponse",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
