import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/lastmile-ai-api-v-2",
    },
    {
      type: "category",
      label: "Dataset",
      items: [
        {
          type: "doc",
          id: "api/create-dataset",
          label: "Create Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/upload-dataset-file",
          label: "Upload Dataset File",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/finalize-single-dataset-file-upload",
          label: "Finalize Single Dataset File Upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset",
          label: "Get Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset-download-url",
          label: "Get Dataset Download URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dataset-view",
          label: "Get Dataset View",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-datasets",
          label: "List Datasets",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/clone-dataset",
          label: "Clone Dataset",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Evaluation",
      items: [
        {
          type: "doc",
          id: "api/evaluate",
          label: "Evaluate",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/evaluate-dataset",
          label: "Evaluate Dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-metrics",
          label: "List Metrics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-metric",
          label: "Get Metric",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Fine Tune Job",
      items: [
        {
          type: "doc",
          id: "api/create-fine-tune-job",
          label: "Create Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-fine-tune-job",
          label: "Submit Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-fine-tune-job",
          label: "Get Fine Tune Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-fine-tune-job-status",
          label: "Get Fine Tune Job Status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-fine-tune-jobs",
          label: "List Fine Tune Jobs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-base-models",
          label: "List Base Models",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Project",
      items: [
        {
          type: "doc",
          id: "api/create-project",
          label: "Create Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-project",
          label: "Get Project",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-projects",
          label: "List Projects",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Pseudo Label Job",
      items: [
        {
          type: "doc",
          id: "api/create-pseudo-label-job",
          label: "Create Pseudo Label Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-pseudo-label-job",
          label: "Submit Pseudo Label Job",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-pseudo-label-job-status",
          label: "Get Pseudo Label Job Status",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/createdatasetrequest",
          label: "CreateDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createdatasetresponse",
          label: "CreateDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/dataset",
          label: "Dataset",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/timestamp",
          label: "Timestamp",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetcolumninfo",
          label: "DatasetColumnInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetlabelstate",
          label: "DatasetLabelState",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploaddatasetfilerequest",
          label: "UploadDatasetFileRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/uploaddatasetfileresponse",
          label: "UploadDatasetFileResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/s-3-presignedpost",
          label: "S3PresignedPost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldsentry",
          label: "FieldsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finalizesingledatasetfileuploadrequest",
          label: "FinalizeSingleDatasetFileUploadRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finalizesingledatasetfileuploadresponse",
          label: "FinalizeSingleDatasetFileUploadResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetfileinfo",
          label: "DatasetFileInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetrequest",
          label: "GetDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetresponse",
          label: "GetDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetdownloadurlrequest",
          label: "GetDatasetDownloadURLRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetdownloadurlresponse",
          label: "GetDatasetDownloadURLResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetviewrequest",
          label: "GetDatasetViewRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/columnfilter",
          label: "ColumnFilter",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/stringcriteria",
          label: "StringCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/numericcriteria",
          label: "NumericCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/rowtagscriteria",
          label: "RowTagsCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/timerangecriteria",
          label: "TimeRangeCriteria",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getdatasetviewresponse",
          label: "GetDatasetViewResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datasetview",
          label: "DatasetView",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/datarow",
          label: "DataRow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/google-protobuf-value",
          label: "google.protobuf.Value",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/struct",
          label: "Struct",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/fieldsentry",
          label: "FieldsEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listvalue",
          label: "ListValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsrequest",
          label: "ListDatasetsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsrequestfilters",
          label: "ListDatasetsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listdatasetsresponse",
          label: "ListDatasetsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clonedatasetrequest",
          label: "CloneDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/clonedatasetresponse",
          label: "CloneDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluaterequest",
          label: "EvaluateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metric",
          label: "Metric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluateresponse",
          label: "EvaluateResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluatedatasetrequest",
          label: "EvaluateDatasetRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/evaluatedatasetresponse",
          label: "EvaluateDatasetResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmetricsrequest",
          label: "ListMetricsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listmetricsresponse",
          label: "ListMetricsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmetricrequest",
          label: "GetMetricRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getmetricresponse",
          label: "GetMetricResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createfinetunejobrequest",
          label: "CreateFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejobconfig",
          label: "FineTuneJobConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createfinetunejobresponse",
          label: "CreateFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitfinetunejobrequest",
          label: "SubmitFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitfinetunejobresponse",
          label: "SubmitFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobrequest",
          label: "GetFineTuneJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobresponse",
          label: "GetFineTuneJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejob",
          label: "FineTuneJob",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/finetunejobresult",
          label: "FineTuneJobResult",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/trainingprogress",
          label: "TrainingProgress",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/modelfile",
          label: "ModelFile",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobstatusrequest",
          label: "GetFineTuneJobStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getfinetunejobstatusresponse",
          label: "GetFineTuneJobStatusResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsrequest",
          label: "ListFineTuneJobsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsrequestfilters",
          label: "ListFineTuneJobsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listfinetunejobsresponse",
          label: "ListFineTuneJobsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbasemodelsrequest",
          label: "ListBaseModelsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listbasemodelsresponse",
          label: "ListBaseModelsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/model",
          label: "Model",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/metricbasemodel",
          label: "MetricBaseModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/modelcard",
          label: "ModelCard",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/valuesentry",
          label: "ValuesEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createprojectrequest",
          label: "CreateProjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createprojectresponse",
          label: "CreateProjectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/project",
          label: "Project",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectrequest",
          label: "GetProjectRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getprojectresponse",
          label: "GetProjectResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsrequest",
          label: "ListProjectsRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsrequestfilters",
          label: "ListProjectsRequestFilters",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/listprojectsresponse",
          label: "ListProjectsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpseudolabeljobrequest",
          label: "CreatePseudoLabelJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pseudolabeljobconfig",
          label: "PseudoLabelJobConfig",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/prompttemplate",
          label: "PromptTemplate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/createpseudolabeljobresponse",
          label: "CreatePseudoLabelJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitpseudolabeljobrequest",
          label: "SubmitPseudoLabelJobRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/submitpseudolabeljobresponse",
          label: "SubmitPseudoLabelJobResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getpseudolabeljobstatusrequest",
          label: "GetPseudoLabelJobStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/getpseudolabeljobstatusresponse",
          label: "GetPseudoLabelJobStatusResponse",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
