/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: [
    "overview",
    "quickstart",
    {
      type: "category",
      label: "AutoEval Developer Platform",
      link: {
        type: "doc",
        id: "autoeval/index",
      },
      items: [
        "autoeval/autoeval-intro",
        "autoeval/metrics",
        {
          type: "category",
          label: "Manage Datasets",
          link: {
            type: "doc",
            id: "autoeval/datasets",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "autoeval/datasets",
            },
          ],
        },
        {
          type: "category",
          label: "LLM Judge Labeling",
          link: {
            type: "doc",
            id: "autoeval/labeling",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "autoeval/labeling",
            },
          ],
        },
        "autoeval/fine-tuning",
        {
          type: "category",
          label: "Models",
          link: {
            type: "doc",
            id: "autoeval/models",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "autoeval/models",
            },
          ],
        },
        "autoeval/guardrails",
      ],
      collapsible: true,
      collapsed: true,
    },

    "sdk", // TODO: saqadri - move into API Reference
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index", // This causes page to display a grid-component of the items
        title: "Overview",
        description: "Some mock description text here",
      },
      items: require("./docs/api/sidebar.js"),
      collapsible: true,
      collapsed: true,
    },
    "deployment",
    {
      type: "link",
      label: "RAG Workbench",
      href: "https://rag.lastmileai.dev",
    },
    {
      type: "link",
      label: "Prompt Management",
      href: "https://aiconfig.lastmileai.dev",
    },
  ],
};

module.exports = sidebars;
