/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // docSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  
  sidebar: [
    'autoeval-platform',
    'overview',
    'quickstart',
    {
      type: 'category',
      label: 'Models',
      link: { 
        type: 'doc', 
        id: 'models',
      },
      items: ['faithfulness', 'correctness', 'toxicity', 'qa', 'summarization'],
      collapsible: true,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Development',
      items: ['sdk'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Tooling',
      items: ['workbench'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Integrations',
      items: ['helicone'],
      collapsible: false,
      collapsed: false,
    },
    {
      type: 'link',
      label: 'Cookbook',
      href: 'https://github.com/lastmile-ai/eval-cookbook',
    }
  ],
};

module.exports = sidebars;